### ISSUE TITLE
"FleetMon" and "Charting Culture" Need Videos

### ISSUE THREAD

**Issue by ezengels** [cns-iu/scimaps#158]
Both these macros link to the creator sites, which don't offer much. Lisel mentioned we have exhibit videos of both, which we should upload and link to instead. I was able to find the FleetMon video on the turing2 server, I'd recommend asking Lisel if you need to find the one for Charting Culture.

**Comment by ezengels** [comment]
Both videos are on turing2, FleetMon is an MP4 and Charting Culture is a WebM.

**Comment by bherr2** [comment]
Don't copy the videos into the repo, but link to them instead (via video tag):

FleetMon: http://idemo.cns.iu.edu/macroscopes/fleetmon.webm
Charting Culture: http://idemo.cns.iu.edu/macroscopes/ChartingCulture.webm
